services:
  - name: db
    type: web
    runtime: docker
    autoDeploy: true
    image:
      url: docker.io/postgres:14
    envVars:
      - key: DATABASE_NAME
        value: postgres
      - key: DATABASE_USERNAME
        value: postgres
      - key: DATABASE_PASSWORD
        value: postgres
      - key: PORT
        value: 5432
    # disks:
    #   - name: postgres_data
    #     mountPath: /var/lib/postgresql/data/
  - name: backend
    type: web
    runtime: docker
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_HOST
        value: db
      - key: DATABASE_NAME
        value: postgres
      - key: DATABASE_USERNAME
        value: postgres
      - key: DATABASE_PASSWORD
        value: postgres
      - key: PORT
        value: 8000
    buildFilter:
      paths:
        - ./backend/**
  - name: frontend
    type: web
    runtime: docker
    autoDeploy: true
    dockerfilePath: ./frontend/Dockerfile
    buildFilter:
      paths:
        - ./frontend/**
    envVars:
      - key: PORT
        value: 5173
