# Generated by Django 5.2.5 on 2025-08-31 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 8, 31, 23, 21, 0, 484841, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
