# Generated by Django 5.2.5 on 2025-08-31 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0003_alter_label_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 8, 31, 23, 38, 46, 600656, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
