# Generated by Django 5.2.5 on 2025-08-31 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 8, 31, 22, 52, 6, 100192, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
