# Generated by Django 5.2.5 on 2025-08-31 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0003_alter_status_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 8, 31, 23, 21, 4, 885098, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
